openapi: 3.0.2
info:
  version: 'v1'
  title: '${project.name}'
  description: |
    ${project.description}
  contact:
    email: '${user.name}@kb.dk'
  license:
    name: '${license.name}'
    url: '${license.url}'
servers:
  #  /api must match servlet-mapping in web.xml
  - url: '/${project.artifactId}/v1'
    description: 'Version 1'

paths:

  /getOaiTargetsConfiguration:
    get:
      tags:
        - '${project.name}'
      summary: 'Retrieve list of configured record bases with update strategy'
      operationId: getOaiTargetsConfiguration
      responses:
        '200':
          description: 'A list of configured record bases with update strategy'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaiTargetList'


  /oaiIngestFull:
    get:
      tags:
        - '${project.name}'
      summary: 'Start full ingest of OAI target into DS-storage'
      operationId: oaiIngestFull
      parameters:
        - name: oaiTarget
          in: query
          description: 'Name of the oai target'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. Returns total number of records ingested.
          content:
            application/json:
              schema:
                type: integer
                format: int32      


components:
  schemas:

    OaiTargetList:
      type: array
      items: 
        $ref: '#/components/schemas/OaiTarget'


    OaiTarget:
      type: object
      properties:
        name:
          type: string
          description: 'Name of the OAI target'
        url:
          type: string
          description: 'Base YRL to the OAI server'                
        set:
          type: string
          description: 'OAI parameter to specify which collection to harvest'                
        recordBase:
          type: string
          description: 'Name of the recordBase when ingesting into DS-storage.'
        decription:
          type: string
          description: 'Human readable name for the collection'                

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
