openapi: 3.0.2
info:
  version: 'v1'
  title: '${project.name}'
  description: |
    ${project.description}
  contact:
    email: '${user.name}@kb.dk'
  license:
    name: '${license.name}'
    url: '${license.url}'
servers:
  #  /api must match servlet-mapping in web.xml
  - url: '/${project.artifactId}/v1'
    description: 'Version 1'

paths:

  /getOaiTargetsConfiguration:
    get:
      tags:
        - '${project.name}'
      summary: 'Retrieve list of configured record bases with update strategy'
      operationId: getOaiTargetsConfiguration
      responses:
        '200':
          description: 'A list of configured record bases with update strategy'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaiTargetList'


  /oaiIngestFull:
    get:
      tags:
        - '${project.name}'
      summary: 'Start full ingest of OAI target into DS-storage'
      operationId: oaiIngestFull
      parameters:
        - name: oaiTarget
          in: query
          description: 'Name of the oai target'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32      

# This definition uses parameters: http://example.com/myservice/v1/hello?alternateHello=Boston
  /hello:
    get:
      tags:
        - '${project.name}'
      summary: 'Request a Hello World message, for testing purposes'
      operationId: getGreeting
      parameters:
        - name: alternateHello
          in: query
          description: 'Optional alternative to using the word ''Hello'' in the reply'
          required: false
          schema:
            type: string
            default: 'World'
      responses:
        '200':
          description: 'A JSON structure containing a Hello World message'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloReply'

components:
  schemas:

    OaiTargetList:
      type: array
      items: 
        $ref: '#/components/schemas/OaiTarget'


    OaiTarget:
      type: object
      properties:
        name:
          type: string
          description: 'Name of the OAI target'
        url:
          type: string
          description: 'URl to the OAI target'                



    HelloReply:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: 'Greeting from the API'

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
